# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Viewfinder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Viewfinder(object):
    def setupUi(self, Viewfinder):
        Viewfinder.setObjectName("Viewfinder")
        Viewfinder.resize(900, 674)
        Viewfinder.setMaximumSize(QtCore.QSize(900, 674))
        self.centralwidget = QtWidgets.QWidget(Viewfinder)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 891, 651))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.Preview = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.Preview.setContentsMargins(0, 0, 0, 0)
        self.Preview.setObjectName("Preview")
        self.Button_row = QtWidgets.QWidget(self.centralwidget)
        self.Button_row.setGeometry(QtCore.QRect(790, 10, 101, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_row.sizePolicy().hasHeightForWidth())
        self.Button_row.setSizePolicy(sizePolicy)
        self.Button_row.setObjectName("Button_row")
        self.gridLayout = QtWidgets.QGridLayout(self.Button_row)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        self.Menu_Button = QtWidgets.QPushButton(self.Button_row)
        self.Menu_Button.setObjectName("Menu_Button")
        self.gridLayout.addWidget(self.Menu_Button, 12, 0, 1, 1)
        self.ISO_label = QtWidgets.QLabel(self.Button_row)
        self.ISO_label.setObjectName("ISO_label")
        self.gridLayout.addWidget(self.ISO_label, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 15, 0, 1, 1)
        self.Exit = QtWidgets.QPushButton(self.Button_row)
        self.Exit.setObjectName("Exit")
        self.gridLayout.addWidget(self.Exit, 14, 0, 1, 1)
        self.ISO_choice = QtWidgets.QComboBox(self.Button_row)
        self.ISO_choice.setObjectName("ISO_choice")
        self.gridLayout.addWidget(self.ISO_choice, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 11, 0, 1, 1)
        self.Zoom_button = QtWidgets.QPushButton(self.Button_row)
        self.Zoom_button.setObjectName("Zoom_button")
        self.gridLayout.addWidget(self.Zoom_button, 9, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 13, 0, 1, 1)
        self.exposure_label = QtWidgets.QLabel(self.Button_row)
        self.exposure_label.setObjectName("exposure_label")
        self.gridLayout.addWidget(self.exposure_label, 2, 0, 1, 1)
        self.exposure_choice = QtWidgets.QComboBox(self.Button_row)
        self.exposure_choice.setObjectName("exposure_choice")
        self.gridLayout.addWidget(self.exposure_choice, 3, 0, 1, 1)
        self.ZoomLabel = QtWidgets.QLabel(self.Button_row)
        self.ZoomLabel.setObjectName("ZoomLabel")
        self.gridLayout.addWidget(self.ZoomLabel, 10, 0, 1, 1)
        self.Capture_button = QtWidgets.QPushButton(self.Button_row)
        self.Capture_button.setObjectName("Capture_button")
        self.gridLayout.addWidget(self.Capture_button, 1, 0, 1, 1)
        self.IR_button = QtWidgets.QPushButton(self.Button_row)
        self.IR_button.setObjectName("IR_button")
        self.gridLayout.addWidget(self.IR_button, 7, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 6, 0, 1, 1)
        Viewfinder.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Viewfinder)
        self.statusbar.setObjectName("statusbar")
        Viewfinder.setStatusBar(self.statusbar)

        self.retranslateUi(Viewfinder)
        QtCore.QMetaObject.connectSlotsByName(Viewfinder)

    def retranslateUi(self, Viewfinder):
        _translate = QtCore.QCoreApplication.translate
        Viewfinder.setWindowTitle(_translate("Viewfinder", "MainWindow"))
        self.Menu_Button.setText(_translate("Viewfinder", "Menu"))
        self.ISO_label.setText(_translate("Viewfinder", "ISO"))
        self.Exit.setText(_translate("Viewfinder", "Exit"))
        self.Zoom_button.setText(_translate("Viewfinder", "Zoom"))
        self.exposure_label.setText(_translate("Viewfinder", "Exposure (e-6s)"))
        self.ZoomLabel.setText(_translate("Viewfinder", "TextLabel"))
        self.Capture_button.setText(_translate("Viewfinder", "Capture"))
        self.IR_button.setText(_translate("Viewfinder", "IR"))
